apiVersion: route.openshift.io/v1
kind: Route
annotations:
  haproxy.router.openshift.io/rewrite-target: /
metadata:
  name: route-unsecured
spec:
  path: "/unnatipune"
  port:
   targetPort: 8080
  to:
    kind: Service 
    name: myapp1

